/**
 * CAPACITOR CONFIGURATION
 *
 * This app ships as a thin Capacitor shell around the production Khatario
 * web app. Instead of bundling a static Next.js export into the APK, the
 * shell simply loads https://<your-host> via `server.url`. That way every
 * deploy to the server is instantly available on user phones — no Play
 * Store resubmission required for ordinary app updates.
 *
 * Configuration values come from environment variables set at build time:
 *   - CAP_SERVER_URL      : Public HTTPS URL of your Next.js deploy.
 *                           Staging: https://staging.khatario.com
 *                           Production (when live): https://app.khatario.com
 *                           Prefer: npm run cap:android:staging:install
 *                           See docs/SERVER_INFRASTRUCTURE.md
 *                           (Native shell appends /login on cold start.)
 *   - CAP_ALLOW_CLEARTEXT : "true" to allow plain http:// for dev. Never in prod.
 *   - CAP_ANDROID_SCHEME  : "https" (default) or "http" for Capacitor's
 *                           internal scheme. Leave default unless debugging.
 *
 * Bluetooth printing is provided by @capacitor-community/bluetooth-le.
 * Android-specific permission declarations live in
 * `android/app/src/main/AndroidManifest.xml` (generated by `cap add android`
 * and then patched — see docs/bluetooth-printing.md).
 */

import type { CapacitorConfig } from '@capacitor/cli';
import { resolveCapacitorServerUrl } from './lib/capacitor/server-url';

/** Cold-starts on /login in the native shell (not marketing /). */
const serverUrl = resolveCapacitorServerUrl(process.env.CAP_SERVER_URL);
const allowCleartext = process.env.CAP_ALLOW_CLEARTEXT === 'true';
const androidScheme = process.env.CAP_ANDROID_SCHEME || 'https';

const config: CapacitorConfig = {
  appId: 'com.khatario.app',
  appName: 'Khatario',
  /**
   * webDir only matters when server.url is undefined, but Capacitor still
   * requires the directory to exist. We keep a tiny offline-fallback page
   * under `capacitor-shell/` that renders a loading spinner + retry button.
   */
  webDir: 'capacitor-shell',
  server: {
    url: serverUrl,
    /**
     * Local branded page when remote server.url is unreachable (cold-start offline).
     * See capacitor-shell/offline.html and docs/COLD_START_OFFLINE.md
     */
    errorPath: 'offline.html',
    cleartext: allowCleartext,
    androidScheme,
  },
  android: {
    allowMixedContent: allowCleartext,
    captureInput: true,
    webContentsDebuggingEnabled:
      process.env.NODE_ENV !== 'production',
  },
  plugins: {
    /**
     * @capacitor-community/bluetooth-le
     * displayStrings localises the built-in pairing prompts that the
     * plugin renders on Android 12+. We expose these here so non-English
     * translations can be wired up later without touching native code.
     */
    BluetoothLe: {
      displayStrings: {
        scanning: 'Scanning for printers…',
        cancel: 'Cancel',
        availableDevices: 'Nearby Bluetooth printers',
        noDeviceFound: 'No Bluetooth printer found',
      },
    },
    /**
     * Embedded in the APK assets for shell version checks (see lib/printer/shell-version.ts).
     * Bump versionCode when native plugins or permissions change; sync android/app/build.gradle.
     */
    KhatarioShell: {
      versionCode: 4,
      versionName: '1.2.1',
    },
  },
};

export default config;
