/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class', // Enable dark mode with class strategy
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          'var(--portal-font-sans, var(--font-inter))',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'Arial',
          'sans-serif',
        ],
      },
      colors: {
        /** Driven by business portal theme via --color-primary-* on :root (fallbacks = default teal). */
        primary: {
          50: 'var(--color-primary-50, #eef2f1)',
          100: 'var(--color-primary-100, #dae2e1)',
          200: 'var(--color-primary-200, #afc2be)',
          300: 'var(--color-primary-300, #7e9b96)',
          400: 'var(--color-primary-400, #47716a)',
          500: 'var(--color-primary-500, #063F35)',
          600: 'var(--color-primary-600, #05362e)',
          700: 'var(--color-primary-700, #042d26)',
          800: 'var(--color-primary-800, #03251f)',
          900: 'var(--color-primary-900, #031c18)',
        },
        /** Driven by org portal theme via --color-accent-* (fallbacks = legacy product accent). */
        accent: {
          50: 'var(--color-accent-50, #fef6ef)',
          100: 'var(--color-accent-100, #feecde)',
          200: 'var(--color-accent-200, #fcd7b8)',
          300: 'var(--color-accent-300, #fabe8b)',
          400: 'var(--color-accent-400, #f8a35a)',
          500: 'var(--color-accent-500, #F58220)',
          600: 'var(--color-accent-600, #d3701c)',
          700: 'var(--color-accent-700, #b05e17)',
          800: 'var(--color-accent-800, #8e4b13)',
          900: 'var(--color-accent-900, #6e3b0e)',
        },
        surface: {
          DEFAULT: 'var(--color-surface)',
          dark: '#1E293B',
        },
        background: {
          DEFAULT: 'var(--color-background)',
          dark: '#0F172A',
        },
        text: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          muted: 'var(--color-text-muted)',
          'primary-dark': '#F8FAFC',
          'secondary-dark': '#CBD5E1',
          'muted-dark': '#94A3B8',
        },
        border: {
          DEFAULT: 'var(--color-border)',
          dark: '#334155',
        },
        success: '#10B981',
        warning: '#F59E0B',
        error: '#EF4444',
        info: '#3B82F6',
      },
      borderRadius: {
        'card': '12px',
        'button': '8px',
        'input': '8px',
      },
      boxShadow: {
        'small': '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)',
        'medium': '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
        'large': '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
      },
      fontSize: {
        '2xs': ['var(--text-2xs)', { lineHeight: 'var(--text-2xs-lh)' }],
        caption: ['var(--text-caption)', { lineHeight: 'var(--text-caption-lh)' }],
        xs: ['var(--text-xs)', { lineHeight: 'var(--text-xs-lh)' }],
        sm: ['var(--text-sm)', { lineHeight: 'var(--text-sm-lh)' }],
        base: ['var(--text-base)', { lineHeight: 'var(--text-base-lh)' }],
        lg: ['var(--text-lg)', { lineHeight: 'var(--text-lg-lh)' }],
        xl: ['var(--text-xl)', { lineHeight: 'var(--text-xl-lh)' }],
        '2xl': ['var(--text-2xl)', { lineHeight: 'var(--text-2xl-lh)' }],
        '3xl': ['var(--text-3xl)', { lineHeight: 'var(--text-3xl-lh)' }],
        'display-sm': ['var(--text-display-sm)', { lineHeight: 'var(--text-display-sm-lh)' }],
        display: ['var(--text-display)', { lineHeight: 'var(--text-display-lh)' }],
        'display-lg': ['var(--text-display-lg)', { lineHeight: 'var(--text-display-lg-lh)' }],
        chart: ['var(--text-chart)', { lineHeight: 'var(--text-chart-lh)' }],
        input: ['var(--text-input)', { lineHeight: 'var(--text-input-lh)' }],
      },
      spacing: {
        'page-x': 'var(--space-page-x)',
        'page-y': 'var(--space-page-y)',
        'page-y-compact': 'var(--space-page-y-compact)',
        'stack-page': 'var(--space-stack-page)',
        'stack-section': 'var(--space-stack-section)',
        'stack-tight': 'var(--space-stack-tight)',
        'card-sm': 'var(--space-card-sm)',
        'card-md': 'var(--space-card-md)',
        'card-lg': 'var(--space-card-lg)',
        'card-xl': 'var(--space-card-xl)',
        'input-x': 'var(--space-input-x)',
        'input-y': 'var(--space-input-y)',
      },
      gap: {
        'stack-page': 'var(--space-stack-page)',
        'stack-section': 'var(--space-stack-section)',
        'stack-tight': 'var(--space-stack-tight)',
      },
    },
  },
  plugins: [],
}

