import {
  BadgeCheck,
  BarChart3,
  Bell,
  BookOpen,
  Building2,
  Calculator,
  Calendar,
  Check,
  CheckCircle2,
  Clock,
  CloudOff,
  CreditCard,
  FileSpreadsheet,
  FileText,
  Globe,
  Headphones,
  Heart,
  IndianRupee,
  Layers,
  Lock,
  Mail,
  MapPin,
  MessageCircle,
  Package,
  PackageCheck,
  Phone,
  Printer,
  QrCode,
  Receipt,
  Rocket,
  ScanBarcode,
  Server,
  Shield,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  Store,
  Truck,
  Users,
  UtensilsCrossed,
  Wallet,
  WifiOff,
  Wrench,
  XCircle,
  Zap,
  type LucideIcon,
} from 'lucide-react';

export const MARKETING_ICONS: Record<string, LucideIcon> = {
  check: Check,
  checkCircle: CheckCircle2,
  xCircle: XCircle,
  badgeCheck: BadgeCheck,
  sparkles: Sparkles,
  star: Star,
  heart: Heart,
  zap: Zap,
  rocket: Rocket,
  shield: Shield,
  lock: Lock,
  server: Server,
  fileText: FileText,
  receipt: Receipt,
  spreadsheet: FileSpreadsheet,
  calculator: Calculator,
  rupee: IndianRupee,
  wallet: Wallet,
  creditCard: CreditCard,
  qrCode: QrCode,
  barcode: ScanBarcode,
  printer: Printer,
  package: Package,
  packageCheck: PackageCheck,
  truck: Truck,
  store: Store,
  cart: ShoppingCart,
  restaurant: UtensilsCrossed,
  wrench: Wrench,
  building: Building2,
  users: Users,
  message: MessageCircle,
  mail: Mail,
  phone: Phone,
  smartphone: Smartphone,
  headphones: Headphones,
  bell: Bell,
  clock: Clock,
  calendar: Calendar,
  chart: BarChart3,
  layers: Layers,
  globe: Globe,
  mapPin: MapPin,
  offline: WifiOff,
  cloudOff: CloudOff,
  book: BookOpen,
};

export const MARKETING_ICON_OPTIONS = Object.keys(MARKETING_ICONS).map((key) => ({
  label: key.replace(/([A-Z])/g, ' $1').replace(/^./, (c) => c.toUpperCase()),
  value: key,
}));

export function MarketingIcon({ name, className }: { name?: string; className?: string }) {
  const Icon = (name && MARKETING_ICONS[name]) || Check;
  return <Icon className={className} strokeWidth={1.75} aria-hidden />;
}
