export type BarcodeType = 'EAN13' | 'UPC' | 'CODE128' | 'QR' | 'CUSTOM';

export interface BarcodeValidationResult {
  isValid: boolean;
  type: BarcodeType | null;
  error?: string;
}

/**
 * Auto-detect barcode type based on length and format
 */
export function detectBarcodeType(barcode: string): BarcodeType | null {
  const cleaned = barcode.trim();
  
  if (!cleaned) return null;
  
  // EAN-13: exactly 13 digits
  if (/^\d{13}$/.test(cleaned)) return 'EAN13';
  
  // UPC-A: exactly 12 digits
  if (/^\d{12}$/.test(cleaned)) return 'UPC';
  
  // Code 128: alphanumeric, variable length (4+ chars)
  if (/^[A-Za-z0-9]{4,}$/.test(cleaned) && cleaned.length <= 48) return 'CODE128';
  
  // QR codes are usually longer and may contain special chars
  if (cleaned.length > 20 && /^[A-Za-z0-9+\-*./: ]+$/.test(cleaned)) return 'QR';
  
  return 'CUSTOM';
}

/**
 * Validate EAN-13 check digit
 */
function validateEAN13(barcode: string): boolean {
  if (!/^\d{13}$/.test(barcode)) return false;
  
  const digits = barcode.split('').map(Number);
  const checkDigit = digits[12];
  
  let sum = 0;
  for (let i = 0; i < 12; i++) {
    sum += digits[i] * (i % 2 === 0 ? 1 : 3);
  }
  
  const calculatedCheck = (10 - (sum % 10)) % 10;
  return calculatedCheck === checkDigit;
}

/**
 * Validate UPC-A check digit
 */
function validateUPC(barcode: string): boolean {
  if (!/^\d{12}$/.test(barcode)) return false;
  
  const digits = barcode.split('').map(Number);
  const checkDigit = digits[11];
  
  let sum = 0;
  for (let i = 0; i < 11; i++) {
    sum += digits[i] * (i % 2 === 0 ? 3 : 1);
  }
  
  const calculatedCheck = (10 - (sum % 10)) % 10;
  return calculatedCheck === checkDigit;
}

/**
 * Validate barcode format and check digit
 */
export function validateBarcode(barcode: string, type?: BarcodeType): BarcodeValidationResult {
  const cleaned = barcode.trim();
  
  if (!cleaned) {
    return { isValid: false, type: null, error: 'Barcode cannot be empty' };
  }
  
  // Check length
  if (cleaned.length < 3) {
    return { isValid: false, type: null, error: 'Barcode must be at least 3 characters' };
  }
  
  if (cleaned.length > 50) {
    return { isValid: false, type: null, error: 'Barcode cannot exceed 50 characters' };
  }
  
  const detectedType = type || detectBarcodeType(cleaned);
  
  if (!detectedType) {
    return { isValid: false, type: null, error: 'Invalid barcode format' };
  }
  
  // Validate check digit for EAN-13 and UPC
  if (detectedType === 'EAN13') {
    if (!validateEAN13(cleaned)) {
      return { isValid: false, type: detectedType, error: 'Invalid EAN-13 check digit' };
    }
  } else if (detectedType === 'UPC') {
    if (!validateUPC(cleaned)) {
      return { isValid: false, type: detectedType, error: 'Invalid UPC-A check digit' };
    }
  }
  
  // Basic format validation for other types
  if (detectedType === 'CODE128' && cleaned.length < 4) {
    return { isValid: false, type: detectedType, error: 'Code128 must be at least 4 characters' };
  }
  
  return { isValid: true, type: detectedType };
}

/**
 * Normalize barcode (remove spaces, convert to uppercase for alphanumeric)
 */
export function normalizeBarcode(barcode: string): string {
  return barcode.trim().replace(/\s+/g, '');
}

export interface GenerateRandomBarcodeOptions {
  /**
   * When true, force the first two digits into the GS1 in-store range
   * (20-29). EAN-13 codes starting with `2` are reserved for retailer
   * internal use and never collide with manufacturer-assigned GTINs, which
   * is exactly what we want for marts assigning their own SKUs.
   */
  inStore?: boolean;
}

/**
 * Generate a random barcode (EAN-13 style with checksum).
 *
 * Pass `{ inStore: true }` to start the code in the GS1 in-store range
 * (20-29) — the right choice for any code generated by a retailer for
 * their own catalogue.
 */
export function generateRandomBarcode(
  options: GenerateRandomBarcodeOptions = {}
): string {
  let barcode = '';

  if (options.inStore) {
    // First digit `2`, second digit 0-9 -> overall prefix 20-29.
    barcode += '2';
    barcode += Math.floor(Math.random() * 10).toString();
    for (let i = 0; i < 10; i++) {
      barcode += Math.floor(Math.random() * 10).toString();
    }
  } else {
    for (let i = 0; i < 12; i++) {
      barcode += Math.floor(Math.random() * 10).toString();
    }
  }

  // EAN-13 checksum
  const digits = barcode.split('').map(Number);
  let sum = 0;
  for (let i = 0; i < 12; i++) {
    sum += digits[i] * (i % 2 === 0 ? 1 : 3);
  }

  const checkDigit = (10 - (sum % 10)) % 10;
  return barcode + checkDigit.toString();
}

// ============================================================================
// WEIGHT / PRICE EMBEDDED EAN-13 (GS1 in-store prefix 2)
// ============================================================================

/**
 * Options for {@link generateWeightEmbeddedBarcode}.
 */
export interface WeightBarcodeOptions {
  /** 4-5 digit PLU code that uniquely identifies the item in this business. */
  pluCode: string;
  /**
   * What the 5-digit measure portion encodes:
   *   - 'weight' -> weight in grams (max 99,999 g)
   *   - 'price'  -> price in paise  (max ₹999.99)
   */
  mode?: 'weight' | 'price';
  /**
   * The measure value:
   *   - when mode='weight' pass the weight in grams (integer 0-99999)
   *   - when mode='price'  pass the price in paise (integer 0-99999)
   *   If omitted, five zeros are used (useful for the printed "parent"
   *   barcode that identifies the item but not a specific weight).
   */
  measure?: number;
}

/**
 * Build a 13-digit EAN-13 barcode using the supermarket weight/price-embedded
 * convention.
 *
 * Structure:
 *   pos 1    : '2'   (GS1 in-store / variable-measure flag)
 *   pos 2    : '1'   for weight mode, '2' for price mode
 *   pos 3-7  : 5-digit zero-padded PLU
 *   pos 8-12 : 5-digit zero-padded measure (grams OR paise)
 *   pos 13   : EAN-13 check digit
 *
 * When a scale scans this code it can parse back both the PLU (to find the
 * item) and the measured value (to compute the line total). The check digit
 * ensures the printer and scale agree on the value.
 */
export function generateWeightEmbeddedBarcode(
  opts: WeightBarcodeOptions
): string {
  const pluRaw = String(opts.pluCode ?? '').replace(/\D/g, '');
  if (!pluRaw || pluRaw.length === 0 || pluRaw.length > 5) {
    throw new Error('PLU code must be 1-5 digits');
  }
  const plu = pluRaw.padStart(5, '0');

  const mode = opts.mode === 'price' ? 'price' : 'weight';
  const modeDigit = mode === 'price' ? '2' : '1';

  const rawMeasure = Math.max(0, Math.floor(opts.measure ?? 0));
  if (rawMeasure > 99999) {
    throw new Error(
      mode === 'price'
        ? 'Price too large (max ₹999.99 per barcode)'
        : 'Weight too large (max 99,999 g per barcode)'
    );
  }
  const measure = String(rawMeasure).padStart(5, '0');

  const body = `2${modeDigit}${plu}${measure}`; // 12 digits
  if (body.length !== 12) {
    throw new Error('Internal: weight barcode body must be 12 digits');
  }

  const digits = body.split('').map(Number);
  let sum = 0;
  for (let i = 0; i < 12; i++) {
    sum += digits[i] * (i % 2 === 0 ? 1 : 3);
  }
  const checkDigit = (10 - (sum % 10)) % 10;
  return body + String(checkDigit);
}

/**
 * Parse a weight-/price-embedded EAN-13 back into its component parts. Returns
 * null if the code is not in the expected GS1 in-store shape.
 */
export function parseWeightEmbeddedBarcode(
  barcode: string
): {
  pluCode: string;
  mode: 'weight' | 'price';
  measure: number;
} | null {
  if (!/^\d{13}$/.test(barcode)) return null;
  if (barcode[0] !== '2') return null;
  const modeDigit = barcode[1];
  if (modeDigit !== '1' && modeDigit !== '2') return null;
  return {
    pluCode: barcode.slice(2, 7).replace(/^0+/, '') || '0',
    mode: modeDigit === '2' ? 'price' : 'weight',
    measure: parseInt(barcode.slice(7, 12), 10),
  };
}
