/**
 * Write knowledge/generated/plans.md from the live plan settings (for review in git).
 * The assistant indexes plans straight from the database, so this file is a readable mirror.
 *
 *   npm run kb:generate            # write the file
 *   npm run kb:generate -- --check # exit 1 when the committed file differs from the database
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { closePool } from '@/lib/db';
import { buildPlansMarkdown } from '@/lib/rag/ingest/plans-source';

const HEADER = '<!-- Generated by `npm run kb:generate` from subscription_plans. Do not edit by hand. -->\n\n';

async function main() {
  const target = join(process.cwd(), 'knowledge', 'generated', 'plans.md');
  let markdown: string;
  try {
    markdown = HEADER + (await buildPlansMarkdown());
  } catch (err) {
    if (process.argv.includes('--check')) {
      console.warn('[kb:generate] database not reachable; skipping plans check:', err instanceof Error ? err.message : err);
      return;
    }
    throw err;
  }

  if (process.argv.includes('--check')) {
    const current = existsSync(target) ? readFileSync(target, 'utf8') : '';
    if (current.replace(/\r\n/g, '\n') !== markdown) {
      console.error('knowledge/generated/plans.md is stale. Run `npm run kb:generate` and commit the result.');
      process.exitCode = 1;
    } else {
      console.log('knowledge/generated/plans.md is up to date.');
    }
    return;
  }

  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, markdown, 'utf8');
  console.log(`Wrote ${target}`);
}

main()
  .catch((err) => {
    console.error('[kb:generate] failed:', err instanceof Error ? err.message : err);
    process.exitCode = 1;
  })
  .finally(() => closePool().catch(() => undefined));
